/**
 * Research tests: the price book, measured factor exposures and the two event
 * studies that calibrate the rubric.
 *
 * The point of these is not to re-assert the headline numbers (those live in
 * docs/reports/, regenerated by `npm run replay`). It is to pin the properties
 * that make the numbers mean anything: no look-ahead, correct sign conventions,
 * clustered statistics reported alongside naive ones, and reproducibility.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { PriceBook } from '../src/ingest/prices.mjs';
import { config } from '../src/config.mjs';
import { exposures, exposureTable, rankBy, factorForTag, FACTOR_IDS, FACTOR_PROXIES, BETA_TAG_MAP } from '../src/research/factors.mjs';
import { runTransmissionStudy } from '../src/research/transmission.mjs';
import { runGapStudy } from '../src/research/gap-study.mjs';
import { renderTransmissionReport, renderGapReport } from '../src/research/report.mjs';
import { round } from '../src/util/num.mjs';

const book = new PriceBook(config.paths.prices).load();

// ------------------------------------------------------------------ price book

test('the bundled dataset is real, multi-year and multi-symbol', () => {
  const s = book.stats();
  assert.ok(s.symbols >= 20, `only ${s.symbols} symbols`);
  assert.ok(s.bars >= 10000, `only ${s.bars} bars`);
  assert.ok(s.from <= '2019-02-01', `dataset starts too late: ${s.from}`);
  assert.ok(s.to >= '2025-09-01', `dataset ends too early: ${s.to}`);
});

test('the factor proxies referenced by the transmission lexicon all exist in the dataset', () => {
  for (const [factor, proxy] of Object.entries(FACTOR_PROXIES)) {
    assert.ok(book.has(proxy), `${factor} proxies to ${proxy}, which is not in the bundled dataset`);
  }
  for (const tag of Object.keys(BETA_TAG_MAP)) {
    assert.ok(FACTOR_IDS.includes(factorForTag(tag)), `betaTag ${tag} maps to an unmeasurable factor`);
  }
  assert.equal(factorForTag('something-invented'), 'mktBeta');
});

test('daily returns, forward returns and event-day returns agree with the bars', () => {
  const bars = book.bars('NVDA');
  assert.ok(bars.length > 500);
  const i = 400;
  const fwd = book.forwardReturn('NVDA', bars[i].date, 5);
  const expected = ((bars[i + 5].close - bars[i].close) / bars[i].close) * 100;
  assert.ok(Math.abs(fwd.pct - expected) < 1e-9);
  assert.equal(fwd.from, bars[i].date);
  assert.equal(fwd.to, bars[i + 5].date);

  const ev = book.eventDayReturn('NVDA', bars[i].date);
  const expectedEv = ((bars[i].close - bars[i - 1].close) / bars[i - 1].close) * 100;
  assert.ok(Math.abs(ev.pct - expectedEv) < 1e-9);
  assert.equal(ev.exact, true);
});

test('forwardReturn refuses to run off the end of the series', () => {
  const bars = book.bars('NVDA');
  const last = bars[bars.length - 1].date;
  assert.equal(book.forwardReturn('NVDA', last, 5), null);
  assert.equal(book.forwardReturn('NVDA', '1800-01-01', 5), null);
});

test('the overnight gap and its resolution are internally consistent', () => {
  const bars = book.bars('SPY');
  let checked = 0;
  for (let i = 200; i < 260; i += 1) {
    const d = bars[i].date;
    const gap = book.overnightGap('SPY', d);
    const res = book.gapResolution('SPY', d);
    assert.ok(Math.abs(gap.pct - ((bars[i].open - bars[i - 1].close) / bars[i - 1].close) * 100) < 1e-9);
    assert.equal(res.date, gap.date);
    assert.equal(res.prevClose, bars[i - 1].close);
    // continuation is the intraday move signed by the gap direction
    assert.ok(Math.abs(res.continuation - res.intradayPct * Math.sign(gap.pct)) < 1e-9);
    if (res.outcome === 'continued') assert.ok(res.continuation > 0);
    if (res.outcome === 'reverted') assert.ok(res.continuation < 0);
    checked += 1;
  }
  assert.ok(checked >= 50);
});

test('realised volatility and volume z-score are plausible and finite', () => {
  for (const sym of ['SPY', 'NVDA', 'TLT']) {
    const vol = book.realisedVol(sym, { window: 60 });
    assert.ok(vol > 0 && vol < 200, `${sym} realised vol ${vol} is not plausible`);
  }
  // A high-beta single name should be more volatile than the broad index.
  assert.ok(book.realisedVol('NVDA', { window: 60 }) > book.realisedVol('SPY', { window: 60 }));
  const bars = book.bars('SPY');
  const vz = book.volumeZ('SPY', bars[bars.length - 2].date);
  assert.ok(Number.isFinite(vz));
});

test('OLS beta of a series against itself is exactly 1', () => {
  const b = book.beta('SPY', 'SPY', { window: 250 });
  assert.ok(Math.abs(b - 1) < 1e-9, `beta(SPY,SPY) = ${b}`);
});

test('beta needs history and returns null rather than a made-up number', () => {
  const bars = book.bars('PLTR');
  assert.equal(book.beta('PLTR', 'SPY', { window: 250, at: bars[5].date }), null);
});

// --------------------------------------------------------------- exposures

test('exposures returns a finite, windowed vector for a liquid name', () => {
  const e = exposures(book, 'NVDA', { window: 252 });
  assert.ok(e);
  assert.equal(e.symbol, 'NVDA');
  assert.ok(e.observations >= 200, `only ${e.observations} observations in a 252-session window`);
  for (const f of FACTOR_IDS) {
    assert.ok(Number.isFinite(e[f]), `${f} is not finite for NVDA`);
  }
  assert.ok(Number.isFinite(e.residualVol) && e.residualVol > 0);
  assert.ok(e.mktBeta > 0.8 && e.mktBeta < 3, `NVDA market beta ${e.mktBeta} is implausible`);
});

test('a proxy measured against itself is pinned to 1 rather than re-estimated', () => {
  const e = exposures(book, 'SPY', { window: 252 });
  assert.equal(e.mktBeta, 1);
});

test('exposures respect the as-of date - no future bars leak into the estimate', () => {
  const past = exposures(book, 'NVDA', { window: 252, at: '2022-06-09' });
  const latest = exposures(book, 'NVDA', { window: 252 });
  assert.ok(past.asOf <= '2022-06-09', `as-of leaked: ${past.asOf}`);
  assert.ok(latest.asOf > past.asOf);
  assert.notEqual(past.growthBeta, latest.growthBeta, 'exposures did not move over three years - the window is not being applied');
});

test('rankBy returns a fully ordered list with ranks', () => {
  const universe = ['NVDA', 'TSLA', 'WMT', 'PFE', 'XOM', 'JPM'];
  const ranked = rankBy(book, universe, 'growthBeta', { descending: true, at: '2025-09-11' });
  assert.ok(ranked.length >= 4);
  for (let i = 1; i < ranked.length; i += 1) {
    assert.ok(ranked[i - 1].value >= ranked[i].value, 'rankBy is not sorted descending');
    assert.equal(ranked[i].rank, i + 1);
  }
  const asc = rankBy(book, universe, 'growthBeta', { descending: false, at: '2025-09-11' });
  assert.equal(asc[0].symbol, ranked[ranked.length - 1].symbol);
});

test('exposureTable drops symbols with insufficient history rather than emitting nulls', () => {
  const table = exposureTable(book, ['NVDA', 'SPY', 'DEFINITELY-NOT-A-SYMBOL'], { window: 252 });
  assert.equal(table.length, 2);
  assert.ok(table.every((r) => Number.isFinite(r.mktBeta)));
});

// ------------------------------------------------------- transmission study

test('the transmission study never uses post-print data to build its ranking', () => {
  const study = runTransmissionStudy(book);
  const scored = study.results.filter((r) => !r.skipped);
  assert.ok(scored.length >= 10);
  for (const r of scored) {
    assert.ok(r.exposuresAsOf, `${r.date} has no exposuresAsOf stamp`);
    assert.ok(r.exposuresAsOf < r.date, `${r.date}: exposures were measured at ${r.exposuresAsOf}, which is not before the print`);
    assert.ok(r.spearman >= -1 && r.spearman <= 1, `${r.date}: rho ${r.spearman} out of range`);
    assert.ok(r.pValue >= 0 && r.pValue <= 1);
    assert.ok(r.n >= 8, `${r.date}: only ${r.n} names ranked`);
    assert.ok(r.topBasket.symbols.length && r.bottomBasket.symbols.length);
    assert.equal(typeof r.spreadDirectionCorrect, 'boolean');
  }
});

test('the transmission study reports the surprise conditioning the rubric depends on', () => {
  const s = runTransmissionStudy(book).summary;
  assert.ok(s.bySurpriseSize.large.n >= 1 && s.bySurpriseSize.medium.n >= 5);
  assert.ok(s.bySurpriseSize.large.meanSpearman >= s.bySurpriseSize.medium.meanSpearman,
    `large surprises (${s.bySurpriseSize.large.meanSpearman}) do not rank better than medium (${s.bySurpriseSize.medium.meanSpearman}) - the 0.30 surprise weight is not empirically supported`);
  assert.ok(Number.isFinite(s.tStat));
  assert.ok(s.positiveRhoPct > 50);
});

test('the transmission study explains every event it declines to score', () => {
  const s = runTransmissionStudy(book).summary;
  assert.equal(s.scored + s.skipped, s.events);
  assert.equal(s.skipReasons.length, s.skipped);
  for (const reason of s.skipReasons) assert.match(reason, /^\d{4}-\d{2}-\d{2}: .+/);
});

test('the transmission study is reproducible', () => {
  const a = runTransmissionStudy(book).summary;
  const b = runTransmissionStudy(book).summary;
  assert.deepEqual(a, b);
});

// ------------------------------------------------------------- gap study

test('the gap study covers a large real sample with both naive and clustered statistics', () => {
  const s = runGapStudy(book).summary;
  assert.ok(s.gaps >= 5000);
  assert.ok(s.symbols >= 20);
  const o = s.overall;
  for (const h of ['fwd1', 'fwd5', 'fwd10']) {
    assert.ok(Number.isFinite(o.excessVsBenchmark[h].t), `${h} naive t missing`);
    assert.ok(Number.isFinite(o.excessDateClustered[h].t), `${h} clustered t missing`);
    assert.ok(o.excessDateClustered[h].dates > 100);
    // Clustering by date must shrink the t-statistic: gaps on the same day are one event.
    assert.ok(Math.abs(o.excessDateClustered[h].t) <= Math.abs(o.excessVsBenchmark[h].t),
      `${h}: clustered t (${o.excessDateClustered[h].t}) exceeds naive t (${o.excessVsBenchmark[h].t}), which would mean clustering inflated significance`);
    assert.ok(Math.abs(o.excessDateClustered[h].mean - o.excessVsBenchmark[h].mean) < 0.05,
      `${h}: clustering should change the standard error, not the mean`);
  }
  assert.ok(Math.abs(o.continuedPct + o.revertedPct + o.flatPct - 100) < 1.5);
});

test('the gap study separates the weekend window from an ordinary overnight', () => {
  const s = runGapStudy(book).summary;
  assert.ok(s.mondayGaps.n > 100 && s.otherWeekdayGaps.n > 1000);
  assert.equal(s.mondayGaps.n + s.otherWeekdayGaps.n, s.gaps);
  assert.ok(s.mondayGaps.medianAbsGapPct >= s.otherWeekdayGaps.medianAbsGapPct,
    'Monday opens should carry at least as much accumulated information as a Tuesday open');
});

test('gap outcomes are consistent with the underlying bars', () => {
  const study = runGapStudy(book);
  for (const row of study.rows.slice(0, 200)) {
    // The study reports rounded figures, so compare at the reported precision.
    const gap = book.overnightGap(row.symbol, row.date);
    assert.equal(round(gap.pct, 3), row.gapPct, `${row.symbol} ${row.date} gap mismatch`);
    assert.equal(row.direction, row.gapPct >= 0 ? 'up' : 'down');
    assert.equal(round(row.intradayPct * Math.sign(row.gapPct), 3), row.continuation);
    assert.ok(['continued', 'reverted', 'flat'].includes(row.outcome));
  }
});

// ------------------------------------------------------------------- reports

test('the study reports render every headline number they claim', () => {
  const t = runTransmissionStudy(book);
  const tText = renderTransmissionReport(t);
  assert.match(tText, /# Macro transmission study/);
  assert.ok(tText.includes(String(t.summary.meanSpearman)));
  assert.ok(tText.includes(String(t.summary.tStat)));
  assert.match(tText, /Caveats/);
  assert.match(tText, /small sample/i);

  const g = runGapStudy(book);
  const gText = renderGapReport(g);
  assert.match(gText, /# Overnight and closed-window gap study/);
  assert.ok(gText.includes(String(g.summary.gaps)));
  assert.ok(gText.includes(String(g.summary.overall.excessDateClustered.fwd5.t)));
  assert.match(gText, /native share, not an rToken/);
  assert.match(gText, /No costs/);
});